title: kimdabin portfolio 
description: 김다빈의 포트폴리오입니다. 
url: https://jekyll-cv.stavrospanakakis.com
baseurl: '/dabbbin.github.io'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
