title: kimdabin portfolio 
description: 김다빈의 포트폴리오입니다. 
url: https://dabbbin.github.io/
baseurl: ""
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
